# @package task
name: "finetune"
output_dir: "models/finetuned_model"
log_dir: "logs"
seed: 42
gpu_ids: null
epochs: 3
precision: "bf16"
max_seq_length: 512
eval_steps: 100
learning_rate: 2e-4
sample_n: null
