# @package task
name: "train_memory"
output_dir: "models/memory_model_custom"
learning_rate: 2e-4
num_train_epochs: 3
precision: "bf16"
seed: 42
max_length: 512
eval_steps: 100
sample_n: 1000
sample_strategy: 'random'
log_predictions: true

optimizer_params:
  # Defines which parts of the model will be trained.
  # Options: "all", "soft_prompt_only"
  trainable_strategy: "all"

loss:
  loss_type: "balanced"
  alpha: 0.2
  temperature: 0.5

strategy:
  # Using sequential strategy for direct training of the custom model.
  # The 'meta' strategy is for training separate PEFT adapters.
  name: "sequential"

extrinsic_validation: "never" # Options: "never", "end", "always"