defaults:
  - base_config
  - _self_
  - task: default_task
  - model: standard
  - dataset: qa_12k
  - prompts: default

output_root: "results"
experiment_subdir: ${now:%Y-%m-%d_%H-%M-%S}
base_output_dir: ${output_root}/${experiment_path}/${experiment_subdir}

hydra:
    run:
        dir: ${base_output_dir}
    sweep:
        dir: ${base_output_dir}
