_target_: src.configs.models.CustomLlamaConfig
model_path: "meta-llama/Llama-3.2-3B"
precision: "bf16"

custom_class_path: src.models.CustomLlamaWithMemory
custom_params:
  memory_slots: 512
  num_memory_layers: 2
