_target_: src.configs.models.PeftLlamaConfig
model_path: "meta-llama/Llama-3.2-3B"
precision: "bf16"

lora_config:
  _target_: peft.LoraConfig
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  inference_mode: False

# memory_config:
#   _target_: peft.PromptTuningConfig
#   num_virtual_tokens: 20
#   inference_mode: False
