frequency: END
metric_type: evaluate
metric_config:
    _target_: src.eval.metrics.evaluate_metric.EvaluateMetricConfig
    metric_name: bertscore
    log_predictions: True
    sample_count: 10
    extra_kwargs:
        lang: en